### ISSUE TITLE
Fails with ABI issues

### ISSUE THREAD

**Issue by languitar** [foxel/seafile-docker#4]
I tried to build the image on my own here, however, executing fails with this error:

```
seafile_1  | Starting seafile server, please wait ...
seafile_1  | Traceback (most recent call last):
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn", line 9, in <module>
seafile_1  |     load_entry_point('gunicorn==19.8.1', 'console_scripts', 'gunicorn')()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/wsgiapp.py", line 61, in run
seafile_1  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/base.py", line 223, in run
seafile_1  |     super(Application, self).run()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/base.py", line 72, in run
seafile_1  |     Arbiter(self).run()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/arbiter.py", line 60, in __init__
seafile_1  |     self.setup(app)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/arbiter.py", line 120, in setup
seafile_1  |     self.app.wsgi()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/base.py", line 67, in wsgi
seafile_1  |     self.callable = self.load()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/wsgiapp.py", line 52, in load
seafile_1  |     return self.load_wsgiapp()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
seafile_1  |     return util.import_app(self.app_uri)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/gunicorn-19.8.1-py2.7.egg/gunicorn/util.py", line 350, in import_app
seafile_1  |     __import__(module)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/seahub/wsgi.py", line 25, in <module>
seafile_1  |     application = get_wsgi_application()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/core/wsgi.py", line 13, in get_wsgi_application
seafile_1  |     django.setup(set_prefix=False)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/__init__.py", line 27, in setup
seafile_1  |     apps.populate(settings.INSTALLED_APPS)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/apps/registry.py", line 108, in populate
seafile_1  |     app_config.import_models()
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/apps/config.py", line 202, in import_models
seafile_1  |     self.models_module = import_module(models_module_name)
seafile_1  |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
seafile_1  |     __import__(name)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/contrib/sessions/models.py", line 3, in <module>
seafile_1  |     from django.contrib.sessions.base_session import (
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/contrib/sessions/base_session.py", line 30, in <module>
seafile_1  |     class AbstractBaseSession(models.Model):
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/db/models/base.py", line 124, in __new__
seafile_1  |     new_class.add_to_class('_meta', Options(meta, app_label))
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/db/models/base.py", line 325, in add_to_class
seafile_1  |     value.contribute_to_class(cls, name)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/db/models/options.py", line 214, in contribute_to_class
seafile_1  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/db/__init__.py", line 33, in __getattr__
seafile_1  |     return getattr(connections[DEFAULT_DB_ALIAS], item)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/db/utils.py", line 211, in __getitem__
seafile_1  |     backend = load_backend(db['ENGINE'])
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/db/utils.py", line 115, in load_backend
seafile_1  |     return import_module('%s.base' % backend_name)
seafile_1  |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
seafile_1  |     __import__(name)
seafile_1  |   File "/opt/seafile/6.3.2/seahub/thirdpart/django/db/backends/mysql/base.py", line 30, in <module>
seafile_1  |     'Did you install mysqlclient or MySQL-python?' % e
seafile_1  | django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: /opt/seafile/6.3.2/seafile/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20).
seafile_1  | Did you install mysqlclient or MySQL-python?
```

**Comment by lamarios** [comment]
Facing the same issue recently while using the image from docker hub. It used to work perfectly until recently.

I fixed it by logging into the container and running the following commands:


```
rm /opt/seafile/6.3.2/seafile/lib/libstdc++.so.6
```
```
ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21 /opt/seafile/6.3.2/seafile/lib/libstdc++.so.6
```
And then restart the container  (without deleting it)

The problem is that next time I delete the container and run it again, it will fail again.

**Comment by foxel** [comment]
Hm... looks like the issue is related to updated ubuntu:16.04. 
Investigating...
